version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run deploy

workflows:
  deploy_and_notify:
    jobs:
      - deploy
