version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo $MY_MESSAGE
            echo 'This is the delivery pipeline'

workflows:
  my-flow:
    jobs:
      - build:
          context:
            - my-context
